#pragma once

#define MF_HTTP_ACK_OK                 "ACK_OK"
#define MF_HTTP_ERR_STATE              "ERR_STATE"
#define MF_HTTP_ERR_LATCHED            "ERR_LATCHED"
#define MF_HTTP_ERR_SCHEMA_INVALID     "ERR_SCHEMA_INVALID"
#define MF_HTTP_ERR_PAYLOAD_TOO_LARGE  "ERR_PAYLOAD_TOO_LARGE"
#define MF_HTTP_ERR_NOT_IMPLEMENTED    "ERR_NOT_IMPLEMENTED"
#define MF_HTTP_ERR_SAFETY_LIMIT       "ERR_SAFETY_LIMIT"
